---
#tasks>main.ymlでnotify: restart pumaを有効にしたらこのhandlerが稼働する
- name: restart puma.service
  become: true
  ansible.builtin.service:
    name: puma.service
    state: restarted
  register: puma-restarted
