all:
  hosts: 
    webappservers:
      ansible_host:  35.77.201.123
      ansible_user: ec2-user
      # host_key_checking: False
      # ansible_ssh_private_key_file: /mnt/c/Users/kawasaki8/Kawasaki1002.pem
      ansible_python_interpreter: /usr/bin/python3

# dbservers:
#   hosts:
#     one.example.com:
#     two.example.com:
