version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.5
  ruby: circleci/ruby@2.0.0

jobs:
  cfn-lint:
    # executor: python/default　実行環境としてOrb由来使わずDockerイメージを使うので無効化
    docker:
      - image: cimg/python:3.12.0

    steps:
      - checkout
      - run: python --version
      - run: pip install --upgrade pip
      - run: pip --version
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3010 -t cloudformation/*.yml
  
  
  execute-ansible:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "${KEY_FINGERPRINT}"
      - run: python --version
      - run: pip install --upgrade pip
      - run: pip --version
      - run: 
          name: install ansible
          command: pip install ansible
      - run: ansible --version
      - run:
          name: Execute Ansible Playbook
          command: ansible-playbook -i ansible/inventory ansible/site.yml
          
  # - ansible/provision:
  #     ansible_version: 2.9.15
  #   # execute-ansible:
  #     executor: ansible/default
  #     inventory: ansible/inventory/target.yml
  #     playbook: ansible/site.yml
    # steps: 
    #   - checkout
    #   - attach_workspace:
    #       at: .
      # - run: cat bash.env >> $BASH_ENV
      # - add_ssh_keys:
      #     fingerprints:
      #       - "${KEY_FINGERPRINT}"
      # - run:
      #     name: Copy SSH Config
      #     command: cp sshconfig/config ~/.ssh/
      # - ansible/install:
      #     version: 2.9.27
      # - ansible/playbook:
      #     playbook: ansible/site.yml
      #     playbook-options: "-i ansible/inventory"
  
  # execute-serverspec:
  #   executor: ruby/default
  #   steps:
  #     - checkout
  #     # サーバーのセットアップ
  #     - run:
  #         name: bundle install
  #         command: |
  #           cd serverspec
  #           gem list -e rails
  #           bundle install --path vendor/bundle

  #     # Serverspecのテストを実行
  #     - run:
  #         name: execute serverspec
  #         command: |
  #           cd serverspec
  #           bundle exec rake spec

workflows:
  CircleCItest:
    jobs:
      - cfn-lint
      - execute-ansible
