version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1.5
  ansible: trustedshops-public/ansible@3.0.2
  ruby: circleci/ruby@2.0.0

jobs:
  execute-ansible:
    executor: ansible/default        
    steps: 
      - checkout
      - attach_workspace:
          at: .
      # - run: cat bash.env >> $BASH_ENV
      - add_ssh_keys:
          fingerprints:
            - "${KEY_FINGERPRINT}"
      # - run:
      #     name: Copy SSH Config
      #     command: cp sshconfig/config ~/.ssh/
      - ansible_version: 2.9.27
      # - ansible/install:
      #     version: 2.9.27
      - inventory: ansible/inventory/target.yml
      - playbook: ansible/site.yml
      # - ansible/playbook:
      #     playbook: ansible/site.yml
      #     playbook-options: "-i ansible/inventory"
  
  # execute-serverspec:
  #   executor: ruby/default
  #   steps:
  #     - checkout
  #     # サーバーのセットアップ
  #     - run:
  #         name: bundle install
  #         command: |
  #           cd serverspec
  #           gem list -e rails
  #           bundle install --path vendor/bundle

  #     # Serverspecのテストを実行
  #     - run:
  #         name: execute serverspec
  #         command: |
  #           cd serverspec
  #           bundle exec rake spec

workflows:
  CircleCItest:
    jobs:
      - execute-ansible
