version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1.5
  ansible: trustedshops-public/ansible@3.0.2
  ruby: circleci/ruby@2.0.0


jobs:

  execute-ansible:
    executor: ansible/default        
    steps: 
    - checkout
    - attach_workspace:
        at: .
    - run: |
          cat bash.env >> $BASH_ENV    
    - add_ssh_keys:
        fingerprints:
          - "${KEY_FINGERPRINT}"
    - ansible/install:
        version: 2.10.7
    - ansible/playbook: 
        playbook: ansible/site.yml
        playbook-options: "-i ansible/inventory"
  
  # execute-serverspec:
  #   executor: ruby/default
  #   steps:
  #     - checkout
  #     # サーバーのセットアップ
  #     - run:
  #         name: bundle install
  #         command: |
  #           cd serverspec
  #           gem list -e rails
  #           bundle install --path vendor/bundle

  #     # Serverspecのテストを実行
  #     - run:
  #         name: execute serverspec
  #         command: |
  #           cd serverspec
  #           bundle exec rake spec

workflows:
  CircleCItest:
    jobs:
      # - cfn-lint
      # - execute-cfn:
      #     requires:
      #       - cfn-lint
      # - execute-ansible:
      #     requires:
      #       - execute-cfn
      - execute-serverspec:
          requires:
            - execute-ansible
