version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1.5
  ansible: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.0.0

jobs:
  execute-ansible:
    executor: ansible/default        
    steps: 
      - checkout
      - attach_workspace:
          at: .
      # - run: cat bash.env >> $BASH_ENV
      - add_ssh_keys:
          fingerprints:
            - SHA256:VqNxLw3cu4KutsL0gB1Q0xBJaJQYxNkKHsAR0aUTv5E
      - ansible/install:
          version: 2.9.27
      - ansible/playbook: 
          playbook: ansible/site.yml
          playbook-options: "-i ansible/inventory"
  
  # execute-serverspec:
  #   executor: ruby/default
  #   steps:
  #     - checkout
  #     # サーバーのセットアップ
  #     - run:
  #         name: bundle install
  #         command: |
  #           cd serverspec
  #           gem list -e rails
  #           bundle install --path vendor/bundle

  #     # Serverspecのテストを実行
  #     - run:
  #         name: execute serverspec
  #         command: |
  #           cd serverspec
  #           bundle exec rake spec

workflows:
  CircleCItest:
    jobs:
      - execute-ansible
