require 'rake'
require 'rspec/core/rake_task'

task :default => [:spec]

namespace :spec do
  desc "Run serverspec"
  RSpec::Core::RakeTask.new(:run) do |t|
    t.pattern = 'spec/**/*_spec.rb'
    t.rspec_opts = '--format documentation'
  end
end
